steps:
# Install
- name: 'gcr.io/cloud-builders/npm:current'
  args: ['install']
# Lint
- name: 'gcr.io/cloud-builders/npm:current'
  args: ['run', 'lint']
# RE-Build
- name: 'gcr.io/cloud-builders/npm:current'
  args: ['rebuild']
# test
- name: 'gcr.io/clfoud-builders/npm:current'
  args: ['run', 'test:headless']
# Build
- name: 'gcr.io/cloud-builders/npm:current'
  args: ['run', 'build:ssr']
# Deploy
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
